### PR TITLE
Search - Back

### PR DESCRIPTION
**Pull request by greyshadows**
#462 

Without changing anything in the URL. Using the history. I guess it should work.

### CODE REVIEW

**Comment by chrisfilo** [comment]
A few things:
- Please amend the commit so it would not include the .nii.gz files and push force. This will avoid blowing up our repo size.
- This solution does not solve anything. When you run `window.history.go(-1)` you will be taken to the previous site, not the previous search. Furthermore, if you 1) search for a term 2) click a link to an image 3) press "back" in your browser you will end up on an empty search page instead of the search page for your term. Imagine how annoying it would be if Google worked this way!

The solution lies somewhere in google custom search documentation. It might require some custom javascript.

**Comment by chrisfilo** [comment]
You can try using "setSearchCompleteCallback" (https://developers.google.com/custom-search/docs/js/cselement-reference#customsearchcontrol-methods) and append ?q=<search term> to the URL (see http://stackoverflow.com/questions/824349/modify-the-url-without-reloading-the-page)

**Comment by vsoch** [comment]
I'm not sure if this is the right PR for this, but it might be useful long term to keep a record of exactly what people are searching for. I haven't looked into it (it may be possible in the admin tools for the search) but if not, would be worth to save some kind of log on our end.

**Comment by chrisfilo** [comment]
Indeed a bit of an offtopic, but all searches are recorded together with
the rest of google analytic information.

**Comment by greyshadows** [comment]
@chrisfilo  1. amend done. Pushed force. 2. Thanks for the reference. I'll look into it.

**Pull request closed without merging**
