### PR TITLE
Fixed handling of tar.gz files

### PR DESCRIPTION
**Pull request by chrisfilo**
Related to #183

### CODE REVIEW

**Comment by ljchang** [comment]
Did you push this to the live website?  Or should I test it locally?

**Comment by chrisfilo** [comment]
It's deployed.

**Comment by ljchang** [comment]
Still not working for me with files created with either Python tarfile module or 'tar -cvfz' shell command.

**Comment by chrisfilo** [comment]
My bad. I gave it one more try (also deployed). I hope it works this time.
If it doesn't I will look into this tmr.

**Comment by ljchang** [comment]
I think it's this line

----> 7 django_file.open()

**Comment by ljchang** [comment]
Still not working.  I'll try testing again in the morning.  Thanks Chris!

**Comment by chrisfilo** [comment]
I had more time and did it properly this time (I wrote some tests). tar.gz
should work now (but it does not solve other issues with big uploads)

**Pull request merged**
