### PR TITLE
Custom templates

### PR DESCRIPTION
**Pull request by chrisfilo**

### CODE REVIEW

**Comment by chrisfilo** [comment]
@asfox this seems to be working. Please tests. Maybe you could also provide some example statmaps in NMT and or Dorris space?

**Comment by asfox** [comment]
I grabbed your changes using: 
git pull https://github.com/chrisfilo/Neurovault.git enh/custom_templates2 

Stat-maps appear fine in the image view, but the collection view fails. It seems to believe that filename for the template-image is "undefined.nii.gz", and the server fails while looking up "/static/images/undefined.nii.gz". 

It might be an easy fix, but I somehow bricked my local copy-- I can't debug until I figure that out. 

Here's a statmap to test with.
[FoxEtAl_PNAS_2015_AT_FDGPET_t.nii.gz](https://github.com/NeuroVault/NeuroVault/files/1916741/FoxEtAl_PNAS_2015_AT_FDGPET_t.nii.gz)

**Comment by chrisfilo** [comment]
Could not replicate. Please make sure you start fresh (`docker-compose rm`).

The map you sent works
image

**Comment by asfox** [comment]
That is the image-view, which I was able to see. Can you see the collection-view? 

I'd be happy to keep debugging, but I got side-bugged:  My local server wont' run, I tried to remove the directory, clone asfox/NeuroVault, and re-pull your changes, but I seem to be missing a step. I'm currently getting a "ERROR:  column statmaps_collection.target_template_image does not exist at character 3045" when I start the server. I think it has something to do with updating the database, but manage.py migrate suggests there are no changes to migrate...

**Comment by chrisfilo** [comment]
image

Did you try `docker-compose rm` followed by `docker-compose up`?

**Comment by asfox** [comment]
You are totally right. I have it working now. It seem to be working great! I haven't noticed any problems yet, and you fixed the callback problem I was having. 👍

**Pull request merged**
