### PR TITLE
Changed default list size for collections, images, collection index and tag listing to 25.

### PR DESCRIPTION
**Pull request by erramuzpe**
This solves issue #352 , but can be discussed if it's appropriate to show that fixed amount of images, tags, collections. Now it is easy to change this default setting. Also, there is the option of showing 'all' instances, in case you thing that would be interesting (it is a bit dangerous too, since it could overload the db when the project grows).

### CODE REVIEW

**Comment by erramuzpe** [comment]
Seems like Docker Engine should be updated.

**Comment by chrisfilo** [comment]
I was - please rebase/merge :)

**Comment by erramuzpe** [comment]
This PR depends on what we agree in the discussion of issue #352

**Comment by erramuzpe** [comment]
@chrisfilo I changed it according to what was agreed, but it is my first time pushing to a PR that was previuosly created and also there have been changes in Master, I'm sorry about the mess. Is it everything ok? (or at least a bit...)

**Comment by chrisfilo** [comment]
Looks ok, but when in doubt rebase/merge.

**Comment by erramuzpe** [comment]
I feel like: 
https://i.imgur.com/XYLwHpM.webm (PR! oh wait, rebase/merge!)

**Pull request merged**
