### PR TITLE
[WIP] Enh/python3

### PR DESCRIPTION
**Pull request by eayoungs**
Updated dependencies for Python 3 compatibility. Identified issues still to be fixed.
- [ ] Conflict with Django core urlresolvers.py

### CODE REVIEW

**Comment by eayoungs** [comment]
Looks like we need to specify re-building neurovault/ahba:py3 to get the ci to pass.

**Comment by chrisfilo** [comment]
Rebuilding this image is too time consuming to do it on CI. It needs to be
built and pushed manually. While you still work on this could you
temporarily push it to your private docker hub username? When all issues
will be resolved I'll push it to docker hub.

BTW make sure pucortex is py3 compatible. Unfortunately we don't have unit
tests for it.

**Comment by eayoungs** [comment]
Understood, @chrisfilo . I will upload the docker image and take a look at pucortex tomorrow.

**Comment by eayoungs** [comment]
For some reason Docker hub is rejecting my push :-\ but I'll get it sorted shortly...

**Comment by chrisfilo** [comment]
I assume you did `docker login` first and are pushing an imaged named `<your_docker_hub_username>/ahba:py3`.

**Pull request closed without merging**
