### PR TITLE
Add warnings about missing metadata

### PR DESCRIPTION
**Pull request by chrisfilo**
When users upload folders or zip files the do not need to input metadata. However, often they are not even aware that there is anything missing. This PR adds warnings about missing metadata.

screenshot from 2016-01-27 11-52-04

### CODE REVIEW

**Comment by vsoch** [comment]
can the spacing of the red warning box be in line with something on the page, for the right and left?

**Comment by chrisfilo** [comment]
I'm sure it can - just don't quite know how to do that. There are a few misalignments in our layout that need to be fixed.

**Comment by vsoch** [comment]
Try setting padding-left / padding-right and margin-left margin-right in the style of the element, either via the warning box itself, or the layer it is sitting in.

**Comment by vsoch** [comment]
It would be best to have a general warning or message class that can be used across pages instead of setting the local style. This class should be defined in a file after bootstrap, otherwise it will not override the default style.

**Comment by chrisfilo** [comment]
I moved the style changes to the main CSS and monkey patched the margin. Other alignment issues will need to wait for another PR.

**Comment by vsoch** [comment]
:monkey: :)

**Pull request merged**
