### PR TITLE
Remove coffeescript

### LINKED ISSUE #84: remove unused NSViewer/coffeescript code
I notice there's a bunch of legacy NSViewer/CoffeeScript code in the templates. I assume this stuff can be removed safely, right? If you're not using my viewer any more, let me know and I'll do some cleanup, as it makes the templates unnecessarily confusing.

### PR DESCRIPTION
**Pull request by abitrolly**
Fixes #84. 4 files converted to JavaScript.
```
✗ grep coffeescript -Ri .
./neurovault/apps/statmaps/static/scripts/viewer.js:// Generated by CoffeeScript 1.6.3
./neurovault/apps/statmaps/templates/statmaps/statisticmap_details.html.haml:{% load coffeescript %}
./neurovault/apps/statmaps/templates/statmaps/statisticmap_details.html.haml:        {% inlinecoffeescript %}
./neurovault/apps/statmaps/templates/statmaps/statisticmap_details.html.haml:        {% endinlinecoffeescript %}
./neurovault/apps/statmaps/templates/statmaps/images_by_tag.html.haml:{% load coffeescript %}
./neurovault/apps/statmaps/templates/statmaps/images_by_tag.html.haml:        {% inlinecoffeescript %}
./neurovault/apps/statmaps/templates/statmaps/images_by_tag.html.haml:        {% endinlinecoffeescript %}
./neurovault/apps/statmaps/templates/statmaps/atlas_details.html.haml:{% load coffeescript %}
./neurovault/apps/statmaps/templates/statmaps/atlas_details.html.haml:        {% inlinecoffeescript %}
./neurovault/apps/statmaps/templates/statmaps/atlas_details.html.haml:        {% endinlinecoffeescript %}
./neurovault/apps/statmaps/templates/statmaps/tags_index.html.haml:{% load coffeescript %}
./neurovault/apps/statmaps/templates/statmaps/tags_index.html.haml:        {% inlinecoffeescript %}
./neurovault/apps/statmaps/templates/statmaps/tags_index.html.haml:        {% endinlinecoffeescript %}
./neurovault/settings.py:    'coffeescript',
./requirements.txt:django-coffeescript
```

### CODE REVIEW

**Comment by abitrolly** [comment]
https://github.com/NeuroVault/NeuroVault/blob/438c97e0ba3e95282d7ca025ca540f014362b1d7/neurovault/apps/statmaps/templates/statmaps/atlas_details.html.haml#L21-L40

https://github.com/NeuroVault/NeuroVault/blob/438c97e0ba3e95282d7ca025ca540f014362b1d7/neurovault/apps/statmaps/templates/statmaps/images_by_tag.html.haml#L7-L16

https://github.com/NeuroVault/NeuroVault/blob/438c97e0ba3e95282d7ca025ca540f014362b1d7/neurovault/apps/statmaps/templates/statmaps/tags_index.html.haml#L6-L19

https://github.com/NeuroVault/NeuroVault/blob/438c97e0ba3e95282d7ca025ca540f014362b1d7/neurovault/apps/statmaps/templates/statmaps/statisticmap_details.html.haml#L90-L108

**Comment by abitrolly** [comment]
From https://github.com/NeuroVault/NeuroVault/blob/master/neurovault/apps/statmaps/urls.py

* tags_index.html.haml is used from https://neurovault.org/images/tags/

**Comment by abitrolly** [comment]
Found `atlas_details.html.haml` through https://neurovault.org/api/atlases/ in https://neurovault.org/images/14228/

**Comment by abitrolly** [comment]
@chrisfilo can be merged now.

**Comment by chrisfilo** [comment]
Awesome contribution! Many thanks!

**Comment by abitrolly** [comment]
Thanks for the tip. ;)

**Pull request merged**
