### PR TITLE
Require login for settings views

### PR DESCRIPTION
**Pull request by burnash**

### CODE REVIEW

**Comment by burnash** [comment]
@chrisfilo The build failed. Looks like something happened to cogatlas:

```
Collecting cognitiveatlas
  Downloading cognitiveatlas-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-AgZxDy/cognitiveatlas/setup.py", line 4, in <module>
        reqs = [line.strip() for line in open('requirements.txt').readlines()]
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by chrisfilo** [comment]
On it https://github.com/CognitiveAtlas/cogat-python/issues/8

**Comment by vsoch** [comment]
Should be fixed - try re-running.

**Comment by vsoch** [comment]
The egg and dist for a python package save the file as "requires.txt" and I was reading from requirements.txt. I returned to the old way of just listing in the file, so it should be resolved.

**Comment by burnash** [comment]
@vsoch @chrisfilo thank you!

**Comment by vsoch** [comment]
boum! @burnash you too! :rowboat:

**Pull request merged**
