### PR TITLE
Added logo and favicon. Remove beta status

### LINKED ISSUE #41: come up with the project logo
for
1 unique appearance
2 adding while listing as a resource in utopia docs annotations

### PR DESCRIPTION
**Pull request by chrisfilo**
Closes #41

### CODE REVIEW

**Comment by vsoch** [comment]
a logo!!!

**Comment by tyarkoni** [comment]
Congratulations! (On the out-of-beta thing. Not the favicon. Though that's pretty cool too.)

**Comment by vsoch** [comment]
It's a brain whale. He's emerging from the diabolical ocean. And he roars MRAAAA!

**Comment by chrisfilo** [comment]
I also created a Twitter account: https://twitter.com/VaultNeuro

**Comment by tyarkoni** [comment]
You so backwards!

Wait, isn't @NeuroVault also you? Have I been advertising for someone else this whole time?

**Comment by vsoch** [comment]
So embarrassing.

**Comment by chrisfilo** [comment]
Sadly it's someone else.

**Comment by tyarkoni** [comment]
April 2011... isn't that, like, before NeuroVault launched? I guess we can't be too mad at them. :p

**Comment by chrisfilo** [comment]
selection_001

I took me half a year to like this logo. I hope it will be quicker for others ;)

**Pull request merged**
