### PR TITLE
Dockerfile cleanup

### PR DESCRIPTION
**Pull request by abitrolly**
#630 research
- npm is not needed for nginx (5f661537)
- apt-get update was already run
- [WORKDIR](https://docs.docker.com/v17.09/engine/reference/builder/#workdir) creates its dirs automatically

### CODE REVIEW

**Comment by chrisfilo** [comment]
We are still dependent on coffeescript - this is probably why your tests fail.

**Comment by abitrolly** [comment]
@chrisfilo looked for coffeescript, but found only Django tags. Can you point me to coffeescript code?

**Comment by chrisfilo** [comment]
It might be that those tags is all that's left over, but that's enough to trigger the error. You would have to remove the tags and the mention of coffeescript in settings.

**Comment by chrisfilo** [comment]
BTW - thanks for helping to clean this up!

**Comment by abitrolly** [comment]
In fact I came for the bounty in #630, but I could not promise to do anything until I know that it is real. May need to much time to learn the codebase, and while I learn it, cleaning the things up is a natural thing to make this time worthy.

**Comment by chrisfilo** [comment]
I see - thanks for clarifying. I can assure you that the bounty is very real.

**Comment by abitrolly** [comment]
This now depends on #641, but I have to admit that my abilities for CoffeeScript are rather limited.

**Pull request merged**
