### PR TITLE
Find similar results as json

### PR DESCRIPTION
**Pull request by erramuzpe**
/images/{pk]/find_similar/json
returns a pandas dataframe as json as in gene_expression_json -> {"data":[[1.0,3.0],[-0.192888910181686,16.0],[0.147546693160353,13.0],[0.083965640541661,14.0],[-0.0595162102504215,17.0],[-0.0354389236538608,15.0]],"columns":["abs_value","image_id"]}

This PR solves #207

### CODE REVIEW

**Comment by erramuzpe** [comment]
https://github.com/NeuroVault/NeuroVault/blob/951dcac11df090d610f35f838465f2f1e7113c36/neurovault/apps/statmaps/views.py#L1003-L1007

I can delete the lines straightforward in this same PR if you want

**Comment by chrisfilo** [comment]
Couple of things:
1. Could you refactor the `find_similar` view to use the new util function `calculate_image_similarity`?
2. Could you rename the `calculate_image_similarity` to `get_similar_images` or something along those lines (since "calculate" is misleading in the current implementation).
3. Could you add a test or two?

**Comment by erramuzpe** [comment]
1.- Yes, but how do I do; 1 return for the json case and another return for the view case?
2.- Ok! sorry
3.- I will try, first time doing it :)

**Comment by chrisfilo** [comment]
As far as I see `calculate_image_similarity` currently returns a pandas dataframe not a JSON. So after some refactoring it could be used inside `find-similar` view (note that I did not suggest replacing `find_similar`)

**Comment by erramuzpe** [comment]
There is a problem with "tags", I will solve it tomorrow!

**Comment by erramuzpe** [comment]
Solved the problem with tags. Let's see how the tests work

**Comment by erramuzpe** [comment]
@chrisfilo check if you like the test . In principle, this and the benchmark are ready to merge.

**Pull request merged**
