### PR TITLE
Update restframework

### PR DESCRIPTION
**Pull request by jbwexler**
also includes the api guide page

### CODE REVIEW

**Comment by chrisfilo** [comment]
Good job! Swagger looks nice! A few things:

 - "try it" option for atlas queries does not work (because swagger does not allow you to include the input parameters)
 - I could not find the query by DOI for collections

**Comment by jbwexler** [comment]
do u think the "try it" option is important to fix? also which query are you referring to? does it use rest framework?

**Comment by chrisfilo** [comment]
The way it is broken right now is quite ugly. We can just disable it if you
prefer it.

I'm talking about this query:
http://neurovault.org/api/collections/?DOI=10.1016/j.neurobiolaging.2012.11.002

**Comment by chrisfilo** [comment]
did you forget to add neurovault/apps/statmaps/tests/test_data/api/DorsalFrontal_thr25_1mm.nii.gz ?

**Pull request merged**
