### PR TITLE
Refactoring of reduced representation

### PR DESCRIPTION
**Pull request by chrisfilo**
* Switch to numpy from joblib (same performance, but allows using File objects)
* Use FileField instead of paths

### CODE REVIEW

**Comment by chrisfilo** [comment]
@vsoch could you have a look?

**Comment by vsoch** [comment]
Sure, I'll test it locally as well... give me a few mins!

**Comment by chrisfilo** [comment]
Only two underscores in a row are problematic: https://docs.djangoproject.com/en/1.8/topics/db/models/#field-name-restrictions

**Comment by vsoch** [comment]
Ok, it looks like single is just for [hidden field "id"](https://stackoverflow.com/questions/14945242/django-query-single-underscore-behaving-like-double-underscore)

**Comment by vsoch** [comment]
What is rationale for moving the reduced_representation back to Image? We had moved it to BaseStatisticalMap for #205 

Other than that, everything seems ok!

 - celery tasks work for new images and updates
 - adding collection with new images worked
 - scatterplot compare and find similar views don't have error
 - api is good!

**Comment by vsoch** [comment]
We maybe should fix #225 on this PR since people's attention was called to the updated API. If not I can add it to my next batch of work.

**Comment by chrisfilo** [comment]
I think we will be able to use reduced_representation to calculate similarity between different types of images in the future and that's why I moved it there. The actual similarity calculation as it stands right now is applicable only to statistical maps so it should stay there, but the reduced_representation file can have more broad uses in the future.

**Comment by vsoch** [comment]
ah, good thinking.

**Pull request merged**
