### PR TITLE
Enabling masking for gene expressions.

### LINKED ISSUE #535: Add cortex, subcortex, whole brain options to gene decoding
As suggested by @tyarkoni

### PR DESCRIPTION
**Pull request by chrisfilo**
Closes #535 
image

### CODE REVIEW

**Comment by tyarkoni** [comment]
I get the following JS error when attempting to switch to subcortex or cortex: "DataTables warning: table id=genes-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7". Any idea?

**Comment by tyarkoni** [comment]
I assume this is driven by an error on the backend that's resulting in no results being generated... will take a look.

**Comment by tyarkoni** [comment]
Ah, the actual error is: "No such file or directory: '/ahba_data/subcortex_mask.npy'". I assume this will work in production; does it need to be included in the docker setup file as well?

**Comment by tyarkoni** [comment]
Never mind, the problem is the user—I forgot to rebuild the docker image.

**Comment by chrisfilo** [comment]
It already is: https://github.com/NeuroVault/NeuroVault/pull/585/files#diff-3254677a7917c6c01f55212f86c57fbfR82

Did you rebuild your container? `docker-compose build`

**Comment by tyarkoni** [comment]
One other minor suggestion (though we can also add this separately): can we link to the Neurosynth maps on the results page, next to the PubMed links? E.g., DRD4 should go to http://neurosynth.org/genes/DRD4/

**Comment by chrisfilo** [comment]
Yup - there is an issue open for it #577. Would prefer to leave it to a separate PR.

**Comment by tyarkoni** [comment]
Cool—as far as I'm concerned, feel free to merge.

**Pull request merged**
