### PR TITLE
Updating install instructions to use docker-machine.

### PR DESCRIPTION
**Pull request by bcipolli**
I was able to run each of the install instructions. The rest of the `docker-compose` commands should be valid; I'm running them now, but my home Internet is too slow for the size of this install to complete anytime soon.

Please take a look and try it out!

### CODE REVIEW

**Comment by chrisfilo** [comment]
Why did you close it? It's not good?

I'd docket hub login really necessary? I can do docker pull without it.

**Comment by bcipolli** [comment]
Somehow the branch got deleted; super weird. I will push again and reopen.

**Comment by bcipolli** [comment]
Sorry about that! It's back :)

**Comment by chrisfilo** [comment]
You also do not need to run docker pull explicitly. docker-compose up will
pull all of the missing images automatically.

**Comment by bcipolli** [comment]
OK, I will update to remove the login and pull. I'm not familiar with these tools, so just followed some tutorials online.

**Comment by bcipolli** [comment]
@chrisfilo Updated

**Pull request closed without merging**
