### PR TITLE
codespell: workflow, config, some typos fixed

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by yarikoptic** [comment]
@adelavega is anybody on lookout after this baby?

**Comment by adelavega** [comment]
Ross Blair is the official maintainer! I can take a look at your PR though.

We did a fair amount of work recently to upgrade to Python 3 and make the
image work so we should be able to easily deploy new features / fixes

**Comment by yarikoptic** [comment]
if you add me as a collaborator I could also carefully and gently press "Merge" once in a while ;)

**Comment by yarikoptic** [comment]
rebased, added ignore, let's see what CI says

**Comment by yarikoptic** [comment]
eh, I think I was not given enough of super powers, still can't merge :-/

**Comment by adelavega** [comment]
oh, no. i'll merge this but since i trust you i'll make an admin. 

pink promise to be good, right?

**Comment by yarikoptic** [comment]
I promise to have only good intentions ! 

[image](https://medium.com/@QuotesCosmos/the-road-to-hell-is-paved-with-good-intentions-17326943c05a)

**Pull request merged**
