### PR TITLE
Switch docs to docker-machine

### LINKED ISSUE #403: Migrate to `docker machine`
When running `boot2docker init`, this is splashed on my screen:
```
  WARNING: The 'boot2docker' command line interface is officially deprecated.

  Please switch to Docker Machine (https://docs.docker.com/machine/) ASAP.

  Docker Toolbox (https://docker.com/toolbox) is the recommended install method.
```

I will try getting this to work via `boot2docker`, then see if I can't get `Docker Machine` running too.

### PR DESCRIPTION
**Pull request by chrisfilo**
How about this @bcipolli instead? Closes #403. Closes #404.

### CODE REVIEW

**Comment by bcipolli** [comment]
If that's more correct, that works for me! I'm not sure that `docker-machine` is just for OSX; there were install instructions for all platforms: https://docs.docker.com/machine/install-machine/

**Comment by chrisfilo** [comment]
docker-machine is only needed if you don't have Linux (otherwise you can use docker natively without the need of a virtual machine)

**Comment by bcipolli** [comment]
Right; the other use-case is Windows, no? :package:

**Comment by chrisfilo** [comment]
Yes  - windows potentially, but I never tested it.

**Pull request merged**
