### PR TITLE
WIP: Metadata support for images

### PR DESCRIPTION
**Pull request by burnash**
This is an implementation of arbitrary key-value fields for images #163.

This pull request is more of a code review than a real PR, as some implementation concepts are subject to change.

To test it locally:
 
 1. Install hstore extension on the database:  `create extension hstore;`
 2. Run `./manage.py migrate`

The key-value storage of choice is hstore as it indeed has more mature support from Django.

I've put the hstore field into the `Image` model, but I'm not sure if it's a best place for it. All data handling happens in `neurovault/apps/statmaps/views.py`. It might be a good idea to move it to DRF. There are two additional endpoints in `urls.py`:
 *  `collection/<cid>/importmetadata`
 *  `collection/<cid>/editmetadata`

Basic backend tests are in `neurovault/apps/statmaps/tests/test_collections.py`

Front-end uses [Handsontable](https://github.com/handsontable/handsontable) to display a data grid. [PapaParse](https://github.com/mholt/PapaParse) to parse input CSV files and [Fuse](https://github.com/krisk/fuse) to assist in fields mapping.

 * `dataimport.js` extends Handsontable to allow a user to map own fields to some predefined fields. It also provides miscellaneous validation procedures.
 * `metadata-import.js` handles file open, CSV parsing and definition of fields and DataImport init.
 * `metadata-edit.js` displays a data grid with image metadata.

### CODE REVIEW

**Comment by burnash** [comment]
@chrisfilo I've rebased PR to 9cf965f and fixed failing travis build (missing hstore init in .travis.yml). It's still failing though mostly to this file absence: `/opt/freesurfer/subjects/fsaverage/mri/brain.nii.gz`. It looks like FreeSurfer is missing.

**Comment by chrisfilo** [comment]
These will be fixed as soon as we merge #182.

**Comment by vsoch** [comment]
This addition of meta data is very exciting - it's going to drive version 2 of advanced image search with filters! I see that we need to merge my current PR to get this underway, I have some research to do this weekend but should be able to make time for the image counter tests.

**Comment by burnash** [comment]
@vsoch Yes, indeed.

I'd love to hear everybody's thoughts on how this advanced image search may look like. What are the use cases?

**Comment by vsoch** [comment]
As a researcher, I would want to be able to filter based on any meta-data available for the image (practical things like smoothing, scanner type, image type, etc.), a cognitive process of interest (cognitive atlas, with more advanced searching actually walking along the tree), one or more brain regions of interest, something about the publication itself (eg, we could learn that a journal is biased to publish results of a specific type), or a specific metric or method of comparison that is better fitting toward the goal of my search, period (this is along the lines of what my research is on.)

**Comment by chrisfilo** [comment]
Could you merge/rebase? The tests should be passing now.

**Comment by burnash** [comment]
I've rebased, and yes, a build has passed

**Comment by chrisfilo** [comment]
Sorry for the late reply. 

Let me begin with saying that I am very excited to merge this. However we need to keep user experience consistent. There are already several "fixed" meta fields describing each statistical map: name, description, map_type, modality etc. It would be good that they also could be updated through the CSV upload mechanism. What is more the custom key/value fields added via CSV file should be exposed through the API in the same way as the "fixed" fields. I don't have any concrete ideas how to implement this, but I would like to avoid user confusion when it comes to types of metadata. I'm looking forward to your proposal.

**Comment by burnash** [comment]
@chrisfilo I agree with you on the user experience consistency. This is why the PR is mostly a code review. Right now I'm experimenting with one way of bringing Image "fixed" fields and custom fields together. This could be done using a [schema mode](http://djangonauts.github.io/django-hstore/#_model_setup) in django-hstore:

```python
class Image(PolymorphicModel, BaseCollectionItem):
    ...
    data = hstore.DictionaryField(blank=True, null=True, schema=[
        {
            'name': 'custom_description',
            'class': 'TextField',
            'kwargs': {
                'blank': True
            }
        }
    ])
```

However it turned out the schema mode doesn't play well with model inheritance:

```python
Unhandled exception in thread started by <function wrapper at 0x114813b90>
Traceback (most recent call last):
  File "NeuroVault/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 222, in wrapper
    fn(*args, **kwargs)
  File "NeuroVault/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 105, in inner_run
    self.validate(display_num_errors=True)
  File "NeuroVault/env/lib/python2.7/site-packages/django/core/management/base.py", line 362, in validate
    return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
  File "NeuroVault/env/lib/python2.7/site-packages/django/core/management/base.py", line 414, in check
    raise CommandError(msg)
django.core.management.base.CommandError: System check identified some issues:

ERRORS:
statmaps.Atlas.custom_description: (models.E006) The field 'custom_description' clashes with the field 'custom_description' from model 'statmaps.image'.
statmaps.NIDMResultStatisticMap.custom_description: (models.E006) The field 'custom_description' clashes with the field 'custom_description' from model 'statmaps.image'.
statmaps.NIDMResultStatisticMap.custom_description: (models.E006) The field 'custom_description' clashes with the field 'custom_description' from model 'statmaps.nidmresultstatisticmap'.
statmaps.StatisticMap.custom_description: (models.E006) The field 'custom_description' clashes with the field 'custom_description' from model 'statmaps.image'.
statmaps.StatisticMap.custom_description: (models.E006) The field 'custom_description' clashes with the field 'custom_description' from model 'statmaps.statisticmap'.
```

Here, I've used a field name `custom_description` to test the approach without removing actual field `description` from BaseCollectionItem to avoid a name clash. But this name clash has appeared nonetheless even with an alternative field name. I'm looking into resolving this.

Another issue: if I move "fixed" fields ("name", "description", etc.) from the `BaseCollectionItem` class these fields will disappear from the derived class `NIDMResults`. Should I add them to the class while keeping the inheritance?

**Comment by chrisfilo** [comment]
I'm closing this for now since you sent an updated PR.

**Pull request closed without merging**
